#pragma once
//unknown
const TCHAR ESTR_UNHANDLEDMSG[] = _T("UNHANDLEDMSG");

//Mouse Event
const TCHAR	ESTR_LBUTTONDOWN[]	= _T("LBUTTONDOWN");
const TCHAR	ESTR_LBUTTONUP[]	= _T("LBUTTONUP");
const TCHAR	ESTR_RBUTTONDOWN[]	= _T("RBUTTONDOWN");
const TCHAR	ESTR_RBUTTONUP[]	= _T("RBUTTONUP");


//